### ISSUE TITLE
Update to 1.4.1 gem?

### ISSUE THREAD

**Issue by Piioo** [RyanScottLewis/jquery-cookie-rails#10]
The latest gem version is 1.3.1.1 and noch 1.4.1.

Would you generate a new gem?

**Comment by donv** [comment]
:+1:

**Comment by Eric-Guo** [comment]
:+1:

**Comment by Eric-Guo** [comment]
@RyanScottLewis [PR 12](https://github.com/RyanScottLewis/jquery-cookie-rails/pull/12) proposed.
