### ISSUE TITLE
Make gem compatible with Rails 5

### ISSUE THREAD

**Issue by Startouf** [RyanScottLewis/jquery-cookie-rails#13]
Currently, there is a 

```
Runtime Dependencies:
railties < 5.0, >= 3.2.0
```

That prevents installation with Rails 5 (railties >= 5.0)

**Comment by RyanScottLewis** [comment]
`jquery-cookie-rails` is no longer maintained as `jquery-cookie` is now unmaintained.

[js-cookie](https://github.com/js-cookie/js-cookie) superceded `jquery-cookie` and therefore [js_cookie_rails](https://github.com/freego/js_cookie_rails) should be used instead of this gem.

**Comment by Schwad** [comment]
Is there a wiki guide for upgrading from jquery-cookie-rails to js_cookie_rails? Came here with same issue.

**Comment by RyanScottLewis** [comment]
Not currently, no.

If I find the time create it (or if someone were to whip one up), I'll drop a link to it in the readme under the "unmaintained" notice.
